name: AWS Update Task Definition

on:
  workflow_dispatch:
    branches:
      - dev
      - main
    inputs:
      environment:
        description: 'Environment to run against'
        type: choice
        options:
          - development
          - production
        default: development
        required: true

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ vars.AWS_REGION }}"
  ENV: "${{ vars.ENV }}"

jobs:
  terraform-apply:
    name: Terraform Apply
    if: needs.terraform-plan.outputs.tfplanExitCode == 2
    runs-on: ubuntu-latest
    environment: "${{ inputs.environment }}"
    needs: [terraform-plan]

    steps:
      # Set AWS credentials and region
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      # Apply new Task Definition to ECS Cluster
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: app-ecs-service
          cluster: app-ecs-cluster
          wait-for-service-stability: true
